sudo: required
language: node_js
services:
- docker
before_install:
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- openssl aes-256-cbc -K $encrypted_537b2eb27cb3_key -iv $encrypted_537b2eb27cb3_iv
-in deploy_key.enc -out ./deploy_key -d
- docker-compose build
- openssl aes-256-cbc -K $encrypted_ced0c438de4d_key -iv $encrypted_ced0c438de4d_iv
- in deploy_key.enc -out ./deploy_key -d
script:
- docker tag weeb:latest $DOCKER_HUB_USERNAME/weeb:production
- docker push $DOCKER_HUB_USERNAME/weeb:production
after_script:
- docker rm -f app
deploy:
provider: script
skip_cleanup: true
script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i deploy_key rezedau@85.255.1.214 ./deploy.sh
env:
global:
- secure: QLcdyfB+mWmKrztHys7fI3xDojojGasrErmUFWFsC1vX36KlpzknpHavnG/Nh+PWsIarRZ+MI/w2Ef811leWj3ObUcmSvozZRzrSst4WhJIsbVX2+18uWk5O4RAKXRgKuXZD3hN1e2xm6zA2ZmaZaO5c7gOEiNY7xCEWseHlRTs5PIEyWO6Sz1oSO+doXm4AlGju830t6vvC3Y0CtXKqAa7A9udxvD8PyeVUDFJklwugiGNecWaVJosQdAW46h5cU3lz17+aTZ6o4IQyLGNdDBTYQONo2oaFja3S41f+q9500ADHv+FCbJNp1kj7ZkKAuVCnzkeqik4MlD/1FRQN9q6QcwlxCf9ZZcPXHoWCumdOt/nU/UVeBHcKF32MI2w5LNUAVCX6VlW0y0UKJ36o8LgvTlpaWNbY+1CwTtV599E4lyl3ld2b4CSM5KKECCL4ujfe9DedM1qYhE4BTGd7db7x6ZQ6yrLUz8830qICdO0LURqH1xxrFjSEGJgMobg30pAxq/95NOqtmla1lZlJRP9WjjfAjrXYvwjUffBw9XIg/DCLePs9mmtVQuPWMvB5/k9LXAEGl8YSp8h4ZWL8lObx6xcvd2xnKAO/etEtGiC4Ie5Nrme+X/K7Lqez1GqndMzkqrN7MGX1oHWovceC/W/RAWQtzbAtKEZOCDVgMyA=
- secure: blh1FtHpQktDdTGFNYxOLuJ4PY7G9eu8nJ8vcVOP4qLb7oaZvRQq9OyNdLrej12VJajxix6DFK4Qk4Ug0fQp49VEMDciZYgpzjua3N5fij1D0QN5yc8/XOXMI60LMdYXPuWn4MgSGMLBOK3vI7g08dtMh7rokcKsOlfoWtV1fuLl4KMLreLVa4RbbCDTZP1ig4YBkv2tIfbpZroguQa026kxCbRqVjZrSGjFZQV72FiX3ypYrCvU8pmePuVZtw7MRH3V7mARBlvBH7h/PciSl0bAEsIWqKqBlevM4S//WdBeC9VxHjbf17eWURuEShCaOcaN4inB8vMvUbdgqC6DZOy8x1gu9WLFxuVrI9t5QPWD4E5g35VLA012lRq+0ji2NDQW6T5ZkU0Gr8fT0xvqdeyBJLKY3Qg6bzj9Q7gW5B0COLgoQwRODWs/XgZxvi37oaMsSDFOzzOefZIfJJXTTjzt5SJw+Ey06/sbz+4FmgoriD4QOPFzidJSEFBaOxNnjUZ043ieu3lNiIxPqrN0oPNe72Xgpm1zzRE35cvOOPs+pjidpNoBBQpQv8yY1n56zdPS/7S+uAbwtyF+oSvMVrOKqVC/fBmQjxmcYClCcNbBp1hUkLSkkhFT53baZWG8qGEJE0Yvk0k2XY8+RrVArlzs04fcShEw4j+A+TrkeJk=
- secure: Cfw88c92BiF0Zgh0jijGALXeOO/f5ku53lQqVhY+kOos9DsmdKrFNtGCcu8ahQyizdGeuVxabry+qvicsmdqvAW/QPry4+JHAvzq9mspeD/VzkV9ohe3by4jcSS162BeTEtEZBcsUWJB3ZF6mAn8aBwhc2ltE+qvI9OHLoSMBlp9m9O6zh5wCI/EVy+xgSLHLuThizemBQR5uYCi1nvW1YgLGNZEYvZaluOnIbzz/nzqJqO35vxF2aqPS70B5PHhFD0Nqrj+u96am1OYDmBsYjTKeESx3VxmLzUzvKdsLtEfFti6VeXJhHKPmXt+0N/E+lXi0T21UdjkkfNbFAgKjFkFDc4cPRztQIXpf3NiViBcxSKLtlsKokPtBd3IV7iyede2yf6v5kU2P42aZqK9kYvGSD2y/I+R/QjmPjHTHiR7NWdMmCW26Qg91at9u1DZWdBm70HQX5TzVCkmzMWTxuAe85s0yw8xTLHvoimOAUy4yybooBm0o+NuLAzhL+uIrI+C2rnx745MIhxp+20wYq5sak1f7/VN/33ua5Fo6dPiEF9/ZUHqcAXcapeco49Ws8AA6TYvxKPpVMfXY8H7sC1iWSOapTbiMct6qmt20FKH8bfYwbYUTDd5YDQjlk70v0N30m6s4ChWKcBwW5zyuctkKohoRqBvAQCM6ruK90I=
  - COMMIT=${TRAVIS_COMMIT::8}
